#!/bin/bash
mcVersion=$(cat .version) || echo "1.17.1" > .version || exit 1
for file in ./tools/scripts/*; do
  chmod +x "$file"
done
rebuildpatches(){
  sh ./tools/scripts/rebuildPatches.sh
}
decompile(){
  chmod +x ./Sticky/sticky.sh
	sh ./tools/scripts/remap_decompile.sh
}
patch(){
	sh ./tools/scripts/applyPatches.sh
}
help(){
	echo "Glucose Script Help"
	echo ""
	echo "Commands:"
	echo ""
	echo "- b, build		| Build (run everything below)"
	echo "- decompile, decom  	| Only decompile"
	echo "- p, patch		| Apply patches"
	echo "- rbp, rebuildpatches   | Create Patches"
	echo "Selected version: $mcVersion"
}
build(){
	decompile
	patch
	gradle build
}
case "$1" in
	"b" | "build") build;;
	"d" | "decompile" | "decom") ./Sticky/sticky.sh $mcVersion;;
	"p" | "patch") patch;;
  "rbp" | "rebuildpatches") rebuildpatches;;
	*) help;;
esac
