name: Java CI With Gradle

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Setup
        run: git submodule update --init; chmod +x Sticky/sticky.sh; wget https://glucosedev.ml/releases/beta/GlucoseLib-1.0.2-BETA.jar; mvn install:install-file -Dfile=GlucoseLib-1.0.2-BETA.jar -DgroupId=ml.glucosedev -DartifactId=GlucoseLib -Dversion=1.0.2-BETA -Dpackaging=jar -DgeneratePom=true; chmod +x ./glucose
      - name: Build API
        run: gradle build -p GlucoseLib/; cp GlucoseLib/build/libs/GlucoseLib-*.jar libs/
      - name: Decompile
        run: ./glucose d
      - name: Patch
        run: ./glucose p
      - name: Build
        run: gradle build
      - name: Upload Jar
        uses: actions/upload-artifact@v2-preview
        with:
          name: glucose-server
          path: build/libs/glucose-server*-all.jar
