# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI With Maven

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: Rampage

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Setup
      run: git submodule update --init; chmod +x Sticky/sticky.sh
    - name: Decompile
      run: ./glucose d
    - name: Patch
      run: ./glucose p
    - name: Build
      run: mvn clean install
