# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI With Maven

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup
      run: git submodule update --init; chmod +x Sticky/sticky.sh; wget https://glucosedev.ml/releases/beta/GlucoseLib-1.0.2-BETA.jar; mvn install:install-file -Dfile=GlucoseLib-1.0.2-BETA.jar -DgroupId=ml.glucosedev -DartifactId=GlucoseLib -Dversion=1.0.2-BETA -Dpackaging=jar -DgeneratePom=true
    - name: Decompile
      run: ./glucose d
    - name: Patch
      run: ./glucose p
    - name: Build
      run: mvn clean install

Glucose/.github/workflows/
in
1.16.5-Sticky
